language: node_js
node_js:
- '6'
sudo: false
notifications:
  email:
  - diego.laucsen@gmail.com
before_install:
  - npm i -g npm gulp
script: npm run test
after_success:
  - test $TRAVIS_NODE_VERSION == '6' && bash <(curl -s https://codecov.io/bash)
